### ISSUE TITLE
How btfhack image build?

### ISSUE THREAD

**Issue by xushuxun** [alibaba/kubeskoop#106]
kubeskoop-exporter use `registry.cn-hangzhou.aliyuncs.com/acs/btfhack:latest` image as initContainer.

Where is this image come from?

**Comment by Lyt99** [comment]
Hi, thanks for your issue!

`btfhack` retrieves btf files from OpenAnolis community . It will detect kernel version, and try to download from [this mirror](https://mirrors.openanolis.cn/coolbpf/btf/x86_64/).

`btfhack` is not open-sourced yet. We're getting `btfhack` into KubeSkoop project, and it will be merged soon.
