### ISSUE TITLE
Is bpf related code opened or not ?

### ISSUE THREAD

**Issue by zhangbo1882** [alibaba/kubeskoop#109]
I cannot see the bpf related code. Is it open source or not ?

**Comment by Lyt99** [comment]
Hi!
bpf code are located in [/bpf](https://github.com/alibaba/kubeskoop/tree/main/bpf). You could find the bpf code for a specific probe by its filename, or `go:generate`  directive in each probe's code.

**Comment by zhangbo1882** [comment]
Thanks @Lyt99. Last week, it always showed errors when I open the directory /bpf. Now it works for me.

**Comment by Lyt99** [comment]
I can't open the bpf code last weekend either, maybe some Github issues. 

Please let me know if you have any other questions. If you don't have any doubt on this problem, you can close this issue. 

Thank you!
