### ISSUE TITLE
Optimization for tracevirtcmdlat

### ISSUE THREAD

**Issue by dzy176** [alibaba/kubeskoop#193]
Hi, @Lyt99 , I have doubts about the metric calculation logic in tracevirtcmdlat.
The current logic is as follows：

```go
if event.Latency > 100000000 {
	p.updateMetrics(VIRTCMD100MS)
} else {
	p.updateMetrics(VIRTCMD)
}
```

Would it be better to change it in this way?  The VIRTCMD metric should contains the VIRTCMD100MS metric.

```go
p.updateMetrics(VIRTCMD)

if event.Latency > 100000000 {
	p.updateMetrics(VIRTCMD100MS)
} 
```

**Comment by Lyt99** [comment]
Hi, thanks for your issue!

It's reasonable for me to make VIRTCMD contain VIRTCMD100MS, and so do other probes like `socketlatency`, `kernellatnecy`, etc.

If you are willing to, cloud you please take a look at these probes, and make a PR for it?

**Comment by dzy176** [comment]
https://github.com/alibaba/kubeskoop/pull/194

**Comment by dzy176** [comment]
PR https://github.com/alibaba/kubeskoop/pull/194, please review 😄😄😄😄
