### ISSUE TITLE
helm repo not found

### ISSUE THREAD

**Issue by clcc2019** [alibaba/kubeskoop#23]
Error: looks like "https://github.com/alibaba/kubeskoop/charts" is not a valid chart repository or cannot be reached: failed to fetch https://github.com/alibaba/kubeskoop/charts/index.yaml : 404 Not Found

**Comment by identifysun** [comment]
@clcc2019 

You can add a charts repository by following the following command?

```shell
$ helm repo add kubeskoop https://github.com/alibaba/kubeskoop/charts
```
