### ISSUE TITLE
无法运行！！！！！

### ISSUE THREAD

**Issue by halleystar** [alibaba/kubeskoop#237]
目前尝试了所有安装方式， 都有问题。 要么就是配置文件没有正确加载，要么是配置文件解析错误，要么是命名不一致。

**Comment by BSWANG** [comment]
最近准备发布1.0版本，所以有很多命名做了规范化，可以看看具体的问题吗？或者钉钉群里沟通

**Comment by halleystar** [comment]
1. kubectl apply -f https://raw.githubusercontent.com/alibaba/kubeskoop/main/deploy/skoopbundle.yaml 默认安装之后kubeskoop-exporter 报错 failed start metrics server: error create probe info: undefined probe info。 导致9102端口没有启动。

**Comment by halleystar** [comment]
2.  这个地方app=skoop-exporter的名字是错误的
![image](https://github.com/alibaba/kubeskoop/assets/5334156/da36a843-18b8-4d70-9a74-ea1345a602dd)

**Comment by BSWANG** [comment]
收到，这两个问题我们尽快修复
