### ISSUE TITLE
getNsInumByPid func

### ISSUE THREAD

**Issue by dzy176** [alibaba/kubeskoop#269]
https://github.com/alibaba/kubeskoop/blob/de036e0e13b90d0019a489086c7003202b5c178e/pkg/exporter/nettop/netns.go#L22C1-L42C3

```go
for _, name := range names {
......
}
```

Hi, why don't we readlink /proc/{{pid}}/ns/net directly？There is no need to loop here

**Comment by jzwlqx** [comment]
hmm...you are right

**Comment by RichardoMrMu** [comment]
https://github.com/alibaba/kubeskoop/pull/278  [change](change:getNsInumByPid readlink /proc/{{pid}}/ns/net directly)
