### ISSUE TITLE
[BUG] connects metrics having same netns in tcpsummary should be accumulated instead of overwrite

### ISSUE THREAD

**Issue by dzy176** [alibaba/kubeskoop#283]
https://github.com/alibaba/kubeskoop/blob/18cc669b7048d6299a4eb0fbc9efdab2d1aae3f7/pkg/exporter/probe/proctcpsummary/proctcp.go#L137C1-L143C40

```go
		resMap[TCPEstablishedConn][nsinum] = est + est6
		resMap[TCPTimewaitConn][nsinum] = tw + tw6
		resMap[TCPTXQueue][nsinum] = tx + tx6
		resMap[TCPRXQueue][nsinum] = rx + rx6
```

Maybe `resMap[TCPEstablishedConn][nsinum] += est + est6  ...... ` is correct?

@Lyt99
@RichardoMrMu      any idea?

**Comment by RichardoMrMu** [comment]
i approve that metrics should be accumulated instead of overwrite. like this https://github.com/alibaba/kubeskoop/pull/284

**Comment by jzwlqx** [comment]
Each pid in the `pidlist` corresponds to a separate netns, and the netns corresponding to any two pids are different. During the `for idx := range pidlist` loop, every netns would only be processed once.

When the loop starts, the value of resMap[TCPEstablishedConn][nsinum] is 0, and there is no need to accumulate during the loop.

**Comment by BSWANG** [comment]
@RichardoMrMu @dzy176 Thanks for reporting the issue.

Based on the discussion above, a socket metric for a netns only needs to be accounted for once, regardless of how many Pids are in that namespace.
