### ISSUE TITLE
Multiple hosts support

### ISSUE THREAD

**Issue by Robin3Chan** [alibaba/kubeskoop#314]
Does the current version support across multiple-k8s clusters or multiple-hosts?

**Comment by BSWANG** [comment]
Across multiple-hosts are supported, not support multiple-clusters. You need install kubeskoop in each cluster.

**Comment by Robin3Chan** [comment]
> Across multiple-hosts are supported, not support multiple-clusters. You need install kubeskoop in each cluster.

For the multiple-hosts-supports, do I need to install for each host? How does skoop-agent aggregate probe data on all hosts?

**Comment by BSWANG** [comment]
> > Across multiple-hosts are supported, not support multiple-clusters. You need install kubeskoop in each cluster.
> 
> For the multiple-hosts-supports, do I need to install for each host? How does skoop-agent aggregate probe data on all hosts?

skoop-agent deploy on each host by kubernetes daemonset, and expose probe data with prometheus metrics api.
