### ISSUE TITLE
skoop crash "error create network" when running kubeskoop

### ISSUE THREAD

**Issue by sdnmw** [alibaba/kubeskoop#55]
When run skoop -s x.x.x.x -d x.x.x.x -p 80 --http:
error create network: the server could not find the requested resource (get ippools.projectcalico.org)

**Comment by sdnmw** [comment]
My environment already installed calico with manifest.It can normally get ipool or list "projectcalico.org" api-resources

**Comment by Lyt99** [comment]
> 

Can you make sure that you're using API in `projectcalico.org/v3`, but not `crd.projectcalico.org/v1`?
`crd.projectcalico.org/v1` is an internal representation of Calico's data, and skoop will not be able to use it.

You can run `kubectl api-resources | grep ippools` to get the API version of the `IPPool` resource. You can also paste the result to this issue to help me diagnose this problem, thank you!
