### ISSUE TITLE
diagnose error: error run collector for pod: cannot get host netns info for node

### ISSUE THREAD

**Issue by blankleee** [alibaba/kubeskoop#57]
![image](https://github.com/alibaba/kubeskoop/assets/65880739/88c2fe63-aa34-4a6a-b551-c41cf5d90adc)

请问下为什么会出现这种情况呢？

**Comment by Lyt99** [comment]
你好，之前发布的`v0.0.1-alpha`版本没有包含目前最新的变更，我发布了一个`v0.0.2-alpha`版本，应该能够解决这个问题。
你可以执行
```bash
go install github.com/alibaba/kubeskoop/cmd/skoop@v0.0.2-alpha
```
重新安装skoop工具，谢谢！

**Comment by Lyt99** [comment]
> 

阿里云上的镜像版本和这边的不太一样，你可以尝试使用`v0.0.1-g6270545-aliyun`这个版本，或者使用昨天发布的镜像`kubeskoop/kubeskoop:v0.0.2-alpha`

**Comment by Lyt99** [comment]
> > 你好，之前发布的`v0.0.1-alpha`版本没有包含目前最新的变更，我发布了一个`v0.0.2-alpha`版本，应该能够解决这个问题。 你可以执行
> > ```shell
> > go install github.com/alibaba/kubeskoop/cmd/skoop@v0.0.2-alpha
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 重新安装skoop命令，谢谢！
> 
> 请问新的kubeskoop-export版本有打新的镜像吗，我从官网上看是registry.cn-hangzhou.aliyuncs.com/acs/kubeskoop-exporter:v0.0.1-g857c8be-aliyun; 改成v0.02不行。ps ( 我主要是用来采集K8S集群容器网络数据的

阿里云上的镜像版本和这边的不太一样，你可以尝试使用`v0.0.1-g6270545-aliyun`这个版本，或者使用昨天发布的镜像`kubeskoop/kubeskoop:v0.0.2-alpha`

**Comment by blankleee** [comment]
> > > 你好，之前发布的`v0.0.1-alpha`版本没有包含目前最新的变更，我发布了一个`v0.0.2-alpha`版本，应该能够解决这个问题。 你可以执行
> > > ```shell
> > > go install github.com/alibaba/kubeskoop/cmd/skoop@v0.0.2-alpha
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > 重新安装skoop命令，谢谢！
> > 
> > 
> > 请问新的kubeskoop-export版本有打新的镜像吗，我从官网上看是registry.cn-hangzhou.aliyuncs.com/acs/kubeskoop-exporter:v0.0.1-g857c8be-aliyun; 改成v0.02不行。ps ( 我主要是用来采集K8S集群容器网络数据的
> 
> 阿里云上的镜像版本和这边的不太一样，你可以尝试使用`v0.0.1-g6270545-aliyun`这个版本，或者使用昨天发布的镜像`kubeskoop/kubeskoop:v0.0.2-alpha`

使用两个镜像都出现相同问题：
执行：
skoop -s xx -d xx -p xx --format json --output a.json
在自建集群： 
F0704 08:19:10.724936  290341 app.go:46] diagnose error: error create node: can not find interface named eth0
在阿里集群：
F0704 08:14:43.859613 1852644 app.go:40] error create network: not support cni type "terway-eniip"

**Comment by blankleee** [comment]
> > > > 你好，之前发布的`v0.0.1-alpha`版本没有包含目前最新的变更，我发布了一个`v0.0.2-alpha`版本，应该能够解决这个问题。 你可以执行
> > > > ```shell
> > > > go install github.com/alibaba/kubeskoop/cmd/skoop@v0.0.2-alpha
> > > > ```
> > > > 
> > > > 
> > > >     
> > > >       
> > > >     
> > > > 
> > > >       
> > > >     
> > > > 
> > > >     
> > > >   
> > > > 重新安装skoop命令，谢谢！
> > > 
> > > 
> > > 请问新的kubeskoop-export版本有打新的镜像吗，我从官网上看是registry.cn-hangzhou.aliyuncs.com/acs/kubeskoop-exporter:v0.0.1-g857c8be-aliyun; 改成v0.02不行。ps ( 我主要是用来采集K8S集群容器网络数据的
> > 
> > 
> > 阿里云上的镜像版本和这边的不太一样，你可以尝试使用`v0.0.1-g6270545-aliyun`这个版本，或者使用昨天发布的镜像`kubeskoop/kubeskoop:v0.0.2-alpha`
> 
> 使用两个镜像都出现相同问题： 执行： skoop -s xx -d xx -p xx --format json --output a.json 在自建集群： F0704 08:19:10.724936 290341 app.go:46] diagnose error: error create node: can not find interface named eth0 在阿里集群： F0704 08:14:43.859613 1852644 app.go:40] error create network: not support cni type "terway-eniip"

请问目前是否必须满足 网卡是ethx + 网络插件是 Flannel 两个条件 ？

**Comment by Lyt99** [comment]
> > > > > 你好，之前发布的`v0.0.1-alpha`版本没有包含目前最新的变更，我发布了一个`v0.0.2-alpha`版本，应该能够解决这个问题。 你可以执行
> > > > > ```shell
> > > > > go install github.com/alibaba/kubeskoop/cmd/skoop@v0.0.2-alpha
> > > > > ```
> > > > > 
> > > > > 
> > > > >     
> > > > >       
> > > > >     
> > > > > 
> > > > >       
> > > > >     
> > > > > 
> > > > >     
> > > > >   
> > > > > 重新安装skoop命令，谢谢！
> > > > 
> > > > 
> > > > 请问新的kubeskoop-export版本有打新的镜像吗，我从官网上看是registry.cn-hangzhou.aliyuncs.com/acs/kubeskoop-exporter:v0.0.1-g857c8be-aliyun; 改成v0.02不行。ps ( 我主要是用来采集K8S集群容器网络数据的
> > > 
> > > 
> > > 阿里云上的镜像版本和这边的不太一样，你可以尝试使用`v0.0.1-g6270545-aliyun`这个版本，或者使用昨天发布的镜像`kubeskoop/kubeskoop:v0.0.2-alpha`
> > 
> > 
> > 使用两个镜像都出现相同问题： 执行： skoop -s xx -d xx -p xx --format json --output a.json 在自建集群： F0704 08:19:10.724936 290341 app.go:46] diagnose error: error create node: can not find interface named eth0 在阿里集群： F0704 08:14:43.859613 1852644 app.go:40] error create network: not support cni type "terway-eniip"
> 
> 请问目前是否必须满足 网卡是ethx + 网络插件是 Flannel 两个条件 ？

skoop命令中默认认为主机的网卡为`eth0`，你可以使用`--flannel-host-interface`或者`--calico-host-interface`明确指定下正确的网卡名称。或许可以添加一个网卡设备的查找列表来缓解这个问题，我近期调查看一下。

目前开源的KubeSKoop只支持`flannel`和`calico`两种网络插件，不支持`terway`网络插件。在阿里云上对`terway`插件进行诊断，可以在ACK控制台的**巡检和诊断-故障诊断**中选择**网络诊断**进行使用。

**Comment by blankleee** [comment]
> > > > > > 你好，之前发布的`v0.0.1-alpha`版本没有包含目前最新的变更，我发布了一个`v0.0.2-alpha`版本，应该能够解决这个问题。 你可以执行
> > > > > > ```shell
> > > > > > go install github.com/alibaba/kubeskoop/cmd/skoop@v0.0.2-alpha
> > > > > > ```
> > > > > > 
> > > > > > 
> > > > > >     
> > > > > >       
> > > > > >     
> > > > > > 
> > > > > >       
> > > > > >     
> > > > > > 
> > > > > >     
> > > > > >   
> > > > > > 重新安装skoop命令，谢谢！
> > > > > 
> > > > > 
> > > > > 请问新的kubeskoop-export版本有打新的镜像吗，我从官网上看是registry.cn-hangzhou.aliyuncs.com/acs/kubeskoop-exporter:v0.0.1-g857c8be-aliyun; 改成v0.02不行。ps ( 我主要是用来采集K8S集群容器网络数据的
> > > > 
> > > > 
> > > > 阿里云上的镜像版本和这边的不太一样，你可以尝试使用`v0.0.1-g6270545-aliyun`这个版本，或者使用昨天发布的镜像`kubeskoop/kubeskoop:v0.0.2-alpha`
> > > 
> > > 
> > > 使用两个镜像都出现相同问题： 执行： skoop -s xx -d xx -p xx --format json --output a.json 在自建集群： F0704 08:19:10.724936 290341 app.go:46] diagnose error: error create node: can not find interface named eth0 在阿里集群： F0704 08:14:43.859613 1852644 app.go:40] error create network: not support cni type "terway-eniip"
> > 
> > 
> > 请问目前是否必须满足 网卡是ethx + 网络插件是 Flannel 两个条件 ？
> 
> skoop命令中默认认为主机的网卡为`eth0`，你可以使用`--flannel-host-interface`或者`--calico-host-interface`明确指定下正确的网卡名称。或许可以添加一个网卡设备的查找列表来缓解这个问题，我近期调查看一下。
> 
> 目前开源的KubeSKoop只支持`flannel`和`calico`两种网络插件，不支持`terway`网络插件。在阿里云上对`terway`插件进行诊断，可以在ACK控制台的**巡检和诊断-故障诊断**中选择**网络诊断**进行使用。

使用指定网卡参数可以运行~
